name: Frontend - Build, Push & Deploy (CI/CD)

on:
  push:
    branches: ["develop"]   # Deploy automatically when merging to develop
  workflow_dispatch:         # Allow manual deployment

jobs:
  build-test-push-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          cd "employee frontend final"
          npm install

      - name: Build Angular app
        run: |
          cd "employee frontend final"
          npm run build --if-present

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/emp-frontend:latest "./employee frontend final"
          docker tag ${{ secrets.DOCKER_USERNAME }}/emp-frontend:latest ${{ secrets.DOCKER_USERNAME }}/emp-frontend:${{ github.sha }}

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/emp-frontend:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/emp-frontend:${{ github.sha }}

      # 🚀 Deploy to Test Server
      - name: Deploy to Test Server via SSH
        if: github.ref == 'refs/heads/develop'
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.TEST_SERVER_IP }}
          username: ${{ secrets.TEST_SERVER_USER }}
          key: ${{ secrets.TEST_SERVER_SSH_KEY }}
          script: |
            docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            docker pull ${{ secrets.DOCKER_USERNAME }}/emp-frontend:latest
            docker stop emp-frontend || true
            docker rm emp-frontend || true
            docker run -d -p 80:80 --name emp-frontend ${{ secrets.DOCKER_USERNAME }}/emp-frontend:latest

      - name: Success
        run: echo "✅ Frontend deployed successfully to test server!"
