name: Frontend - Build & Test Docker Image (CI)

on:
  pull_request:
    branches: ["develop", "main"]  # run CI when a PR targets develop or main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Set up Node.js (if your frontend uses Node/Angular/React)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: |
          cd emp_frontend
          npm install

      # 4️⃣ Build Docker image
      - name: Build Docker image
        run: |
          docker build -t emp-frontend:test ./emp_frontend

      # 5️⃣ Run frontend tests inside Docker
      - name: Run frontend tests
        run: |
          docker run --rm emp-frontend:test sh -c "npm test"  # replace with your test command

      # 6️⃣ Success message
      - name: Success
        run: echo "Frontend Docker image built and tests passed successfully!"
